### ISSUE TITLE
Google Bug Error Template

### ISSUE THREAD

**Issue by PetarDimitrov86** [PetarDimitrov86/SoftUniQA-Playground#2]
Submitter
Petar Dimitrov, lbmikesmith@gmail.com

Date Seen
20/03/2017 15:08

Versions
v. 2.10
Windows 10 Pro
Google Chrome

Bug Description
Missing Product review comment form on product page. The requirement can be found here - LINK

Severity
Minor

Steps to Reproduce
1.	Navigate to home page
2.	Select category „Women”
3.	Select subcategory “Dresses”
4.	Select product “Printed Dress”

Actual Behavior
No product review form on Product page.

Expected Behavior
Form should be present on Product page and user should be able to write comments/reviews. [2.2.1](LINK) 

Troubleshooting/Testing Steps Attempted
N/A

Workaround
N/A

**Comment by PetarDimitrov86** [comment]
тест

**Comment by softuniqa** [comment]
дасдссада

**Comment by PetarDimitrov86** [comment]
Better close this, in case the lecturer mistakes it for an exam issue

**Comment by PetarDimitrov86** [comment]
CLOSE!
